name: Bump and release

on:
  workflow_dispatch:

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
      - name: Create bump and changelog
        run: |
          pixi run -e default cz bump --changelog-to-stdout > body.md
          REVISION=$(pixi run -e default cz version --project)
          git push origin main --follow-tags
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITIZEN }}
      - name: Checkout stable
        uses: actions/checkout@v4
        with:
          ref: stable
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Merge main -> stable
        run: |
          git rebase origin/main
          git push origin stable
