name: Publish

on:
  workflow_dispatch:

jobs:
  bump-version:
    environment: pypi
    runs-on: ubuntu-latest
    name: "Publish new release"
    steps:
      - name: Check out
        uses: actions/checkout@v4
        with:
          ref: stable
          fetch-depth: 0
          token: "${{ secrets.COMMITIZEN }}"
      - name: Config git
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Merge main -> stable
        run: |
          git rebase origin/main
          git push origin stable
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.46.0
          cache: true
      - name: Publish
        run: |
          pixi run -e py310 publish
          pixi run -e py311 publish
          pixi run -e py312 publish